# Generated by Django 5.2.3 on 2025-07-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='duracion_semanas',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='curso',
            name='camada',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
